config/routes.rb
Rails.application.routes.draw do
  resources :site_contatcts, as: :contacts
  resources :site_contatcts
  get '/contacts', to: 'site_contatcts#index'
  resources :product_sizes
  resources :flavors
  resources :categories
  resources :products
  #resources 'contacts', only: [:new, :create]

  devise_for :users
  root to: 'products#index'
  get 'about_us', to: 'welcome#about_us', as: :about_us
  get 'midia', to: 'welcome#midia', as: :midia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flavor.rb
class Flavor < ApplicationRecord
  has_many :product_flavors
  has_many :products, through: :product_flavors
  validates_uniqueness_of :name


end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor.destroy
    respond_to do |format|
      format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name)
    end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.erb
<%= simple_form_for(@flavor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flavors/edit.html.erb
<h1>Editing Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Show', @flavor %> |
<%= link_to 'Back', flavors_path %>

app/views/flavors/index.html.erb
<h1>Flavors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flavors.each do |flavor| %>
      <tr>
        <td><%= flavor.name %></td>
        <td><%= link_to 'Show', flavor %></td>
        <td><%= link_to 'Edit', edit_flavor_path(flavor) %></td>
        <td><%= link_to 'Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flavor', new_flavor_path %>

app/views/flavors/new.html.erb
<h1>New Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Back', flavors_path %>

app/views/flavors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @flavor.name %>
</p>

<%= link_to 'Edit', edit_flavor_path(@flavor) %> |
<%= link_to 'Back', flavors_path %>