config/routes.rb
Rails.application.routes.draw do
  resources :site_contatcts, as: :contacts
  resources :site_contatcts
  get '/contacts', to: 'site_contatcts#index'
  resources :product_sizes
  resources :flavors
  resources :categories
  resources :products
  #resources 'contacts', only: [:new, :create]

  devise_for :users
  root to: 'products#index'
  get 'about_us', to: 'welcome#about_us', as: :about_us
  get 'midia', to: 'welcome#midia', as: :midia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_flavors, dependent: :destroy
  has_many :flavors, dependent: :destroy, through: :product_flavors

  has_many :product_sizes, dependent: :destroy
  accepts_nested_attributes_for :product_sizes, reject_if: :all_blank, allow_destroy: true
  validates_uniqueness_of :name
  mount_uploader :product_image, ProductImageUploader
  crop_uploaded :product_image
  validates_presence_of :name, :category, :product_image,:product_sizes, :description
  def min_value
    unless self.product_sizes.empty?
    "R$ #{(('%.2f' %  self.product_sizes.minimum(:value)).sub'.',',')}"
  end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @categories = Category.all
    @flavors = Flavor.all
    @sizes = []

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.product_sizes.build()
  end

  # GET /products/1/edit
  def edit
    @product.product_sizes.build()  if (@product.product_sizes.empty? || @product.product_sizes.nil?)


  end

  # POST /products
  # POST /products.json
  def crop

  end
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html {
          if product_params[:product_image].present?
            render :crop ## Render the view for cropping
          else
            redirect_to @product, notice: 'Product was successfully created.'
          end
        }
        format.json {render :show, status: :created, location: @product}

      else
        puts @product.errors.messages.inspect
        format.html {render :new}
        format.json {render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update

    respond_to do |format|
      if @product.update(product_params)
        format.html {
          if product_params[:product_image].present?
            render :crop ## Render the view for cropping
            else
              redirect_to @product, notice: 'Product was successfully updated.'
          end
        }
        format.json {render :show, status: :ok, location: @product}
      else
        format.html {render :edit}
        format.json {render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html {redirect_to products_url, notice: 'Product was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:product_image,
                                    :product_image_crop_x,
                                    :product_image_crop_y,
                                    :product_image_crop_w,
                                    :product_image_crop_h,
                                    :category_id,
                                    :description, :full_description,
                                    :name, product_sizes_attributes: [:id, :name, :weight, :height, :width, :depth, :value, :_destroy])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_dashboard_menu.html.erb
<div class="panel-group dashboard-menu" id="accordion">
  <div class="panel panel-default dashboard-menu-panel ">
    <div class="panel-heading dashboard-menu-head">
      <h4 class="panel-title dashboard-menu-title ">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Produtos</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse  in dashboard-menu-content-container">
      <div class="panel-body">
        <table class="table">
          <% @categories.each do |category| %>
              <tr>
                <td>
                  <%= image_tag 'cakes.png' if category.name == "Bolos" %>
                  <%= image_tag 'brownies.png' if category.name == "Brownies" %>
                  <%= image_tag 'brownie_jar.png' if category.name == "Brownies no pote" %>
                  <%= image_tag 'brigadeiros.png' if category.name == "Brigadeiros" %>
                  <%= link_to "#{category.name}", products_path, class: 'mel-dark menu-link' %>
                  <!--<span class="glyphicon glyphicon-pencil text-primary"></span><a href="http://www.jquery2dotnet.com">Articles</a>-->
                </td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>

</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
    <%= f.error_notification %>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img_prev')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(200);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
    <div class="form-inputs">
        <div class="row">
          <div class="col-xs-12 col-lg-12">
            <div class="row">
              <div class="col-xs-12 col-lg-7 col-md-6 col-sm-6 ">
                <%= f.association :category, label: 'Categoria:' %>
                <%= f.input :name, label: 'Nome:', placeholder: 'Ex.: Bolo de Chocolate, Bolo Kitkat' %>
                <%= f.input :description, label: 'Pequena Descrição:', placeholder: 'Ex.: Pequena descrição exibida na pagina principal' %>
                <%= f.input :full_description, label: 'Descrição Completa:', placeholder: 'Descrição completa' %>
                <%= (image_tag @product.product_image, class: 'img-responsive') unless @product.product_image.nil? || @product.product_image.to_s.empty? %>
                <label>* Imagem</label>
                <%= f.file_field :product_image, label: 'Imagem:', :id => "upload", :onchange => "readURL(this)" %>
                <img id="img_prev" src="#" alt=""/>
              </div>
              <div class="col-xs-12 col-lg-5 col-md-6 col-sm-6">
                <%= f.association :flavors, label: 'Sabores:' %>
                <br>
                <div class="container-fluid">
                  <%= f.simple_fields_for :product_sizes do |product_size| %>
                      <%= render 'products/product_size_fields', :f => product_size %>
                  <% end %>
                  <div class="btn-add-product_size-container">
                    <%= link_to_add_association "Adicionar Tamanho", f, :product_sizes, class: 'btn btn-success btn-block  ' %>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-sm-12">
            <div class="form-actions">
              <%= f.button :submit, "Cadastrar Produto" %>
            </div>
          </div>
        </div>
      </div>
<% end %>

app/views/products/_product_size_fields.html.erb
<div id="nested-fields" class="row nested-fields product-size-fields">
  <div class="category_from_list">
      <div class="col-xs-7">
        <%= f.input :name, label: 'Tamanho:', placeholder: 'Ex.: Pequeno, 100 Unidades' %>
      </div>
      <!--<div class="col-xs-3">
        <%# f.input :weight, label: 'Peso:', placeholder: 'Ex.: 1kg, 100g, 300ml ' %>
      </div>-->
      <div class="col-xs-5">
        <%= f.input :value, label: 'Valor:', placeholder: 'Ex.: 119.99 ' %>
      </div>
      <div class="col-xs-4">
        <%# f.input :width, label: 'Largura:', placeholder: 'Ex.: 50cm' %>
      </div>
      <div class="col-xs-4">
        <%# f.input :height, label: 'Altura:', placeholder: 'Ex.: 50cm' %>
      </div>
      <div class="col-xs-4">
        <%# f.input :depth, label: 'Profundidade:', placeholder: 'Ex.: 50cm' %>
      </div>
    <div class="col-xs-12 center-align btn-rmv-product_size-container">
      <%= link_to_remove_association "X", f, class: 'btn btn-block btn-danger ' %>
    </div>
    <br>
  </div>
</div>
<%# link_to_add_association 'or create a new tag', f, :category %>

app/views/products/crop.html.erb
<%= form_for @product do |f| %>
    <%= f.cropbox :product_image%>
    <%= f.previewbox :product_image %>
    <%= f.submit 'Crop' %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1 class="mel-dark">Editar Produto</h1>
  <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<%content_for :title do %>
Mel Doceria | Produtos
<% end %>
<div class="container-fluidr" style=" margin: 0px 20px 0 20px; ">
  <br>
  <div class="row">
    <div class="col-lg-2 col-md-3 col-sm-4  ">

     <%= render ('dashboard_menu') %>
    </div>

    <div class="col-lg-10 col-md-9 col-sm-8 ">
      <% i = 0 %>

      <% @products.each do |product| %>
          <% if i%3==0 && i != 0 %>
              </div>
          <% end %>
          <% if i == 0 || i%3==0 %>
              <div class="row">
          <% end %>
          <div class="col-lg-4   col-sm-12 col-xs-12 ">
            <div class="thumbnail product-container" style="">
              <div class="product-image-container ">
                <%= link_to (image_tag product.product_image,  class: 'product-image img-responsive'), product %>
                <div class="middle">
                  <div class="product-description"><%= link_to product.description, product, class: 'product-description-link' %></div>
                </div>
              </div>
              <div class="caption ">
                <div class="container-fluid product-header-container">
                  <h3 class="center"><%= link_to "#{product.name}", product, class: 'mel-dark menu-link' %></h3>
                  <h4 class="value-green "><%= "A partir de #{product.min_value}" %></h4>
                  <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a>
                    <a href="#" class="btn btn-default" role="button">Button</a></p>-->
                </div>
              </div>
            </div>
          </div>
          <% i += 1 %>
      <% end %>
      </div>
      </div>
</div>
<br>


<br>

app/views/products/new.html.erb
<div class="container">
<h1 class="mel-dark">Cadastrar Produto</h1>
<%= render 'form', product: @product %>
</div>
<%# link_to 'Back', products_path %>

app/views/products/show.html.erb
<br>
<br>
<div class="container-fluid product-show-container ">

  <div class="row">
    <div class="col-sm-12">
      <div class="product-show-header-container">
        <h1 class=" text-center mel-dark">
          <%= @product.name %>
        </h1></div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-7">
      <div class="product-show-image-container">
        <%= image_tag @product.product_image, class: ' img-responsive' %>
        <br>
        <br>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="product-show-description-container">
        <h3 class="mel-dark">Descrição:</h3>
        <table class="table">
          <tbody>
          <tr>
          <td>
        <h4 class="purple">
          <%= ( (@product.full_description.nil? ) || (@product.full_description.empty?) ) ?  @product.description : @product.full_description %></h4>
          </td>
          </tr>
          </tbody>
        </table>
      </div>
      <br>
      <div class="product-show-sizes-container">
        <h3 class="mel-dark">Tamanhos:</h3>
        <table class="table" >
          <tbody>
          <% @product.product_sizes.each do |product_size| %>
              <tr>
                <td class="purple "><h4><%= product_size.name %></h4></td>
                <td><%# product_size.weight %></td>
                <td><%# product_size.width %></td>
                <td><%# product_size.height %></td>
                <td><%# product_size.depth %></td>
                <td class="value-green "> <h4> <%= "#{product_size.value_f}" %></h4></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <%# link_to 'Edit', edit_product_path(@product) %>
  <%# link_to 'Back', products_path %>
</div>