config/routes.rb
Rails.application.routes.draw do
  resources :site_contatcts, as: :contacts
  resources :site_contatcts
  get '/contacts', to: 'site_contatcts#index'
  resources :product_sizes
  resources :flavors
  resources :categories
  resources :products
  #resources 'contacts', only: [:new, :create]

  devise_for :users
  root to: 'products#index'
  get 'about_us', to: 'welcome#about_us', as: :about_us
  get 'midia', to: 'welcome#midia', as: :midia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_uniqueness_of :name
  validates_presence_of :name

end

app/models/contact.rb
class Contact < MailForm::Base
  validates_presence_of :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Contato Via Site MelDoceria.com.br",
        :to => "soares.cunha.joao@gmail.com, contato@meldoceria.com.br",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/flavor.rb
class Flavor < ApplicationRecord
  has_many :product_flavors
  has_many :products, through: :product_flavors
  validates_uniqueness_of :name


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_flavors, dependent: :destroy
  has_many :flavors, dependent: :destroy, through: :product_flavors

  has_many :product_sizes, dependent: :destroy
  accepts_nested_attributes_for :product_sizes, reject_if: :all_blank, allow_destroy: true
  validates_uniqueness_of :name
  mount_uploader :product_image, ProductImageUploader
  crop_uploaded :product_image
  validates_presence_of :name, :category, :product_image,:product_sizes, :description
  def min_value
    unless self.product_sizes.empty?
    "R$ #{(('%.2f' %  self.product_sizes.minimum(:value)).sub'.',',')}"
  end
  end
end

app/models/product_flavor.rb
class ProductFlavor < ApplicationRecord
  belongs_to :product
  belongs_to :flavor
  validates_uniqueness_of :flavor_id, scope: :product
end

app/models/product_product_size.rb
class ProductProductSize < ApplicationRecord
  belongs_to :product_size
  belongs_to :product
  validates_presence_of :value
  validates_uniqueness_of :product_size_id, scope: :product
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  validates_presence_of :name, :value
  def value_f
    "R$ #{(('%.2f' % self.value).sub'.',',')}"
    #R$ #{'%.2f' %(self.value).to_s}"
  end

end

app/models/product_size_category.rb
class ProductSizeCategory < ApplicationRecord
  has_many :product_sizes
  has_many :products, through: :product_sizes
  validates_uniqueness_of :name
  validates_presence_of :name
end

app/models/site_contatct.rb
class SiteContatct < ApplicationRecord
  validates_presence_of  :name, :email, :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor.destroy
    respond_to do |format|
      format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carousel_helper.rb
# app/helpers/carousel_helper.rb

module CarouselHelper
  def carousel_for(images)
    Carousel.new(self, images).html
end
  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end
    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: @uid, class: 'carousel slide ')
    end
    private
    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view
    def indicators
      items = images.count.times.map {|index| indicator_tag(index)}
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end
    def indicator_tag(index)
      options = {
          class: (index.zero? ? 'active' : ''),
          data: {
              target: @uid,
              slide_to: index
          }
      }
      content_tag(:li, '', options)
    end
    def slides
      items = images.map.with_index {|image, index| slide_tag(image, index.zero?)}
      content_tag(:div, safe_join(items), class: 'carousel-inner ')
    end
    def slide_tag(image, is_active)
      options = {
          class: (is_active ? 'item active ' : 'item '),
      }
      content = content_tag(:div, image_tag(image, class: 'img-carousel img-responsive'), options)
      content << content_tag(:div,  {class:'carousel-caption' }) do
          content_tag(:h2, 'Heading')
        end
    end
    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end
    def control_tag(direction)
      options = {
          class: "#{direction} carousel-control",
          data: {slide: direction == 'left' ? 'prev' : 'next'}
      }
      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{@uid}", options)
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/helpers/product_sizes_helper.rb
module ProductSizesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_contatcts_helper.rb
module SiteContatctsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 text-center footer-text">
        Mel Doceria © Copyright 2015-2017. Todos os Direitos Reservados.
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center footer-text">

        (21) 98276-4239 | contato@meldoceria.com.br
      </div>
    </div>

  </div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= yield :title %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'fav_icon.ico' %>
  <script type="application/javascript">

  </script>

</head>
<body>

<div class="container-fluid index-container" id="world-background">
  <%= render 'layouts/navbar/navbar' %>
  <div class="page-content">
    <div class="container" style="max-width: 1200px;">
      <%= render 'layouts/shared/flashes' %>
    </div>

    <%= yield %>
  </div>

</div>

</body>
<script type="application/javascript">
    setWorldBackgroundHeight();
    window.addEventListener('resize', setWorldBackgroundHeight);
    // window.resize callback function
    function setWorldBackgroundHeight() {
        document.getElementById("world-background").style.minHeight = "" + ($(window).height()) + "px";
    }
</script>
<%= render 'layouts/footer' %>


</html>

app/views/layouts/navbar/_navbar.html.erb
<div class="container-fluid  ">
  <div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
      <nav class="navbar navbar-default navbar-fixed-top " id="navbar">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header pull-left brand-img-container ">
            <%= link_to (image_tag 'logo_trans.png', class: "img-responsive ", height: 150, alt: "Facebook Page"), root_path, class: "navbar-brand" %>
          </div>
          <!-- 'Sticky' (non-collapsing) right-side menu item(s) -->
          <div class="navbar-header pull-left ">
            <li class="dropdown visible-xs visible-sm visible-md collapsed-flag-selector">
<%# render "layouts/navbar/navbar_locale_selector" %>
            </li>
          </div>
          <div class="navbar-header ">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
<%# render "layouts/navbar/navbar_slogan_text" %>
            </ul>
            <ul class="nav navbar-nav navbar-right nav-items-container " id="nav-items-container">
              <% if user_signed_in? == true %>
                  <li class="<%= "active" if current_page?(products_path) %>"><%= link_to "Produtos", products_path%></li>
                  <li class="<%= "active" if current_page?(about_us_path) %>"><%= link_to "Quem Somos", about_us_path %></li>
                  <li class="<%= "active" if current_page?(midia_path) %>"><%= link_to "Mídia", midia_path %></li>
                  <li class="<%= "active" if current_page?(new_contact_path) %>"><%= link_to "Contato", new_contact_path %></li>
            <% else
                   user_signed_in? == false %>
                  <li class="<%= "active" if current_page?(products_path) %>"><%= link_to "Produtos", products_path%></li>
                  <li class="<%= "active" if current_page?(about_us_path) %>"><%= link_to "Quem Somos", about_us_path %></li>
                  <li class="<%= "active" if current_page?(midia_path) %>"><%= link_to "Mídia", midia_path %></li>
                  <li class="<%= "active" if current_page?(new_contact_path) %>"><%= link_to "Contato", new_contact_path %></li>
                  <!-- <li class="<%# "active" if (current_page?(user_session_path)) %>"><%# link_to "Login".to_s.capitalize, new_user_session_path %></li> -->

                  <li class="<%# "active" if current_page?(supported_coins_path) %>"><%# link_to t(:supported_coins).to_s.capitalize, supported_coins_path %></li>
                  <li class="<%# "active" if current_page?(prices_and_fees_path) %>"><%# link_to t(:fees).to_s.capitalize, prices_and_fees_path %></li>
                  <li class="<%# "active" if current_page?(contact_path) %>"><%# link_to t(:contact).to_s.capitalize, new_contact_path %></li>
              <% end %>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>
    <div class="col-xs-2"></div>

  </div>

</div>

app/views/layouts/navbar/_navbar_locale_selector.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
  <!--<%= image_tag "en_50x32_roundCorner.png" %>-->
  <span class="caret"></span>
</a>
<ul class="dropdown-menu">
  <%I18n.available_locales.each do |l|%>
    <% if l != I18n.locale %>
    <% end %>
<% end %>
</ul>

app/views/layouts/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>